/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        // Reads client/src/styles/tokens.css — never restate hex here.
        'bg-page': 'var(--bg-page)',
        'bg-surface': 'var(--bg-surface)',
        'bg-input': 'var(--bg-input)',
        'bg-subtle': 'var(--bg-subtle)',
        'bg-hover': 'var(--bg-hover)',
        'text-primary': 'var(--text-primary)',
        'text-strong': 'var(--text-strong)',
        'text-secondary': 'var(--text-secondary)',
        'text-muted': 'var(--text-muted)',
        accent: 'var(--accent)',
        'accent-subtle': 'var(--accent-subtle)',
        'border-card': 'var(--border-card)',
        'border-nav': 'var(--border-nav)',
        'border-subtle': 'var(--border-subtle)',
        'status-ok': 'var(--status-ok)',
        'status-warning': 'var(--status-warning)',
        'status-critical': 'var(--status-critical)',
        'status-danger': 'var(--status-danger)',
        'status-forecast-alert': 'var(--status-forecast-alert)',
        'status-ok-fill': 'var(--status-ok-fill)',
        'status-warning-fill': 'var(--status-warning-fill)',
        'status-critical-fill': 'var(--status-critical-fill)',
        'status-danger-fill': 'var(--status-danger-fill)',
        'status-ok-tint': 'var(--status-ok-tint)',
        'status-warning-tint': 'var(--status-warning-tint)',
        'status-critical-tint': 'var(--status-critical-tint)',
        'status-danger-tint': 'var(--status-danger-tint)',
        'cat-1': 'var(--cat-1)',
        'cat-1-tint': 'var(--cat-1-tint)',
        'cat-2': 'var(--cat-2)',
        'cat-2-tint': 'var(--cat-2-tint)',
        'cat-3': 'var(--cat-3)',
        'cat-3-tint': 'var(--cat-3-tint)',
        'cat-4': 'var(--cat-4)',
        'cat-4-tint': 'var(--cat-4-tint)',
        'cat-5': 'var(--cat-5)',
        'cat-5-tint': 'var(--cat-5-tint)',
        'cat-6': 'var(--cat-6)',
        'cat-6-tint': 'var(--cat-6-tint)',
        'cat-fallback': 'var(--cat-fallback)',
        'cat-fallback-tint': 'var(--cat-fallback-tint)',
        'form-success': 'var(--form-success)',
        'form-error': 'var(--form-error)',
      },
      backgroundImage: {
        'brand-gradient': 'var(--brand-gradient)',
        'brand-gradient-strong': 'var(--brand-gradient-strong)',
        'brand-stripe': 'var(--brand-stripe)',
      },
      borderRadius: {
        sm: 'var(--radius-sm)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        pill: 'var(--radius-pill)',
      },
      boxShadow: {
        sm: 'var(--shadow-sm)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
      },
      fontFamily: {
        sans: 'var(--font-sans)',
        mono: 'var(--font-mono)',
      },
      fontSize: {
        '2xs': ['var(--text-2xs)', { lineHeight: '1rem' }],
      },
      transitionDuration: {
        fast: 'var(--duration-fast)',
        base: 'var(--duration-base)',
        slow: 'var(--duration-slow)',
      },
    },
  },
  plugins: [],
};
